name: build-test-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: echo txt file
        run: echo "$(cat hello_world.txt)"
      - name: setup node ver 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: run npm install and build and test
        run: npm install && npm run build

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: run npm install and test
        run: npm install && npm run test

  deploy:
     needs: [test]
     runs-on: ubuntu-latest
     permissions:
       contents: write
       pages: write
       id-token: write
     environment:
       name: production
       url: ${{steps.deployment.outputs.page_url }}
     steps:
       - name: check repo
         uses: actions/checkout@v3
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
       - name: config github pg
         uses: actions/configure-pages@v3
         with:
          static_site_generator: next
       - name: run npm install and build and test
         run: npm install && npm run build
       - name: upload atifa
         uses: actions/upload-pages-artifact@v1
         with:
           path: "./out"
       - name: deploy pg
         id: deployment
         uses: actions/deploy-pages@v1
          
