name: build-test-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: echo txt file
        run: echo "$(cat hello_world.txt)"
      - name: setup node ver 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: run npm install and build and test
        run: npm install && npm run build

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: run npm install and test
        run: npm install && npm run test
          
          
